
Neos:
  Fusion:
    rendering:
      exceptionHandler: Neos\Fusion\Core\ExceptionHandlers\ThrowingHandler
    enableContentCache: false
    defaultContext:
      Testing.String: Neos\Eel\Helper\StringHelper
      Testing.Utility: Neos\Fusion\Tests\Functional\TypoScriptObjects\Fixtures\Helper\UtilityHelper
