Neos:

  ContentRepository:

    # Configure available content dimensions for nodes, after adding a dimension the database has to be filled with
    # the dimension default values.
    # Also add named presets with fallback chains that can happen in your dimensions.
    #
    # Example
    #
    #   contentDimensions:
    #     language:
    #       default: mul_ZZ
    #       defaultPreset: 'all'
    #       presets:
    #         'all':
    #           values: ['mul_ZZ']
    #
    #     persona:
    #       default: everybody
    #       defaultPreset: 'all'
    #       presets:
    #         'all':
    #           values: ['everybody']
    contentDimensions: {  }

    # Configures defaults for node label generation
    labelGenerator:
      eel:
        defaultContext:
          String: Neos\Eel\Helper\StringHelper
          Array: Neos\Eel\Helper\ArrayHelper
          Date: Neos\Eel\Helper\DateHelper
          Configuration: Neos\Eel\Helper\ConfigurationHelper
          Math: Neos\Eel\Helper\MathHelper
          Json: Neos\Eel\Helper\JsonHelper
          I18n: Neos\Flow\I18n\EelHelper\TranslationHelper
          q: Neos\Eel\FlowQuery\FlowQuery::q

    unstableInternalWillChangeLater:
      testing:
        projectorsToBeReset: {}
        # DoctrineDbal: Neos\ContentGraph\DoctrineDbalAdapter\Domain\Repository\ContentGraph
        activeContentGraphs: {}
      projection:
        defaultProjectorsToBeBlocked:
          'Neos\ContentRepository\Projection\ContentStream\ContentStreamProjector': true
          'Neos\ContentRepository\Projection\Workspace\WorkspaceProjector': true
    nodeAccessorFactories:
      contentSubgraph:
        position: end
        className: Neos\ContentRepository\NodeAccess\Implementation\ContentSubgraphAccessorFactory

