type: dictionary
properties:
  Neos:
    type: dictionary
    properties:
      Fusion:
        type: dictionary
        additionalProperties: false
        properties:
          rendering:
            type: dictionary
            additionalProperties: false
            properties:
              exceptionHandler:
                type: string
                format: class-name
              innerExceptionHandler:
                type: string
                format: class-name
          debugMode:
            type: boolean
          enableContentCache:
            type: boolean
          defaultContext:
            type: dictionary
            additionalProperties:
              type: string
              format: class-name
          dsl:
            type: dictionary
            additionalProperties:
              type: string
              format: class-name
          Afx:
            type: dictionary

