Neos:
  EventSourcedNeosAdjustments:
    contentDimensions:
      resolution:
        uriPathSegmentDelimiter: '_'
    fusion:
      enableObjectTreeCache: false
  Flow:
    http:
      middlewares:
        'detectContentSubgraph':
          position: 'befoure routing'
          middleware: 'Neos\EventSourcedNeosAdjustments\EventSourcedRouting\Http\DetectContentSubgraphMiddleware'
    error:
      debugger:
        ignoredClasses:
          'Neos\\ContentRepository\\Domain\\Model\\NodeType': true
          'Neos\\Eel\\CompilingEvaluator': true
          'Neos\\EventSourcedContentRepository\\Domain\\Projection\\Content\\PropertyCollection': true
          'Neos\\Fusion\\FusionObjects\\Helpers\\FusionPathProxy': true
          'Neos\\ContentRepository\\Domain\\Service\\NodeTypeManager': true
          'Neos\\ContentRepository\\DimensionSpace\\DimensionSpace\\DimensionSpacePoint.*': true

  Fusion:
    defaultContext:
      Neos.EventSourcedNeosAdjustments.Workspace: Neos\EventSourcedNeosAdjustments\Fusion\Helper\WorkspaceHelper
      # TODO: maybe this helper must be exposed as Neos.Node
      Neos.EventSourcedNeosAdjustments.Node: Neos\EventSourcedNeosAdjustments\Fusion\Helper\NodeHelper
      Neos.Link: Neos\EventSourcedNeosAdjustments\Fusion\Helper\LinkHelper
      Neos.Caching: Neos\EventSourcedNeosAdjustments\Fusion\Helper\CachingHelper
      Neos.EventSourcedNeosAdjustments.Ui.NodeInfo: Neos\EventSourcedNeosAdjustments\Ui\Fusion\Helper\NodeInfoHelper
      Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions: Neos\EventSourcedNeosAdjustments\Ui\Fusion\Helper\ContentDimensionsHelper
  Neos:
    modules:
      management:
        submodules:
          workspaces:
            controller: 'Neos\EventSourcedNeosAdjustments\WorkspaceModule\Controller\WorkspacesController'
    fusion:
      autoInclude:
        Neos.EventSourcedNeosAdjustments: true
    Ui:

      configurationDefaultEelContext:
        Neos.EventSourcedNeosAdjustments.Workspace: Neos\EventSourcedNeosAdjustments\Fusion\Helper\WorkspaceHelper
        Neos.EventSourcedNeosAdjustments.Ui.NodeInfo: Neos\EventSourcedNeosAdjustments\Ui\Fusion\Helper\NodeInfoHelper
        Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions: Neos\EventSourcedNeosAdjustments\Ui\Fusion\Helper\ContentDimensionsHelper

      initialState:
        cr:
          nodes:
            byContextPath: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.defaultNodesForBackend(site, documentNode, controllerContext)}'
            siteNode: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.serializedNodeAddress(site)}'
            documentNode: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.serializedNodeAddress(documentNode)}'
          contentDimensions:
            # TODO: re-enable dimensions
            byName: '${Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions.contentDimensionsByName()}'
            active: '${subgraph.dimensionSpacePoint.toLegacyDimensionArray()}'
            allowedPresets: '${Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions.allowedPresetsByName(subgraph.dimensionSpacePoint)}'
          workspaces:
            personalWorkspace: '${Neos.EventSourcedNeosAdjustments.Workspace.getPersonalWorkspace()}'
        ui:
          contentCanvas:
            src: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.uri(Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.nodeAddress(documentNode), controllerContext)}'
            contextPath: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.serializedNodeAddress(documentNode)}'
      documentNodeInformation:
        metaData:
          documentNode: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.serializedNodeAddress(documentNode)}'
          siteNode: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.serializedNodeAddress(site)}'

          previewUrl: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.createRedirectToNode(controllerContext, q(documentNode).context({workspaceName: documentNode.context.workspace.baseWorkspace.name}).get(0))}'

          contentDimensions:
            active: '${documentNode.dimensionSpacePoint.toLegacyDimensionArray()}'
            allowedPresets: '${Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions.allowedPresetsByName(subgraph.dimensionSpacePoint)}'
          documentNodeSerialization: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.renderNodeWithPropertiesAndChildrenInformation(documentNode, controllerContext)}'
          url: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.uri(Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.nodeAddress(documentNode), controllerContext)}'

      changes:
        types:
          'Neos.Neos.Ui:Property': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\Property
          'Neos.Neos.Ui:CreateInto': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\Create
          'Neos.Neos.Ui:CreateAfter': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\CreateAfter
          'Neos.Neos.Ui:CreateBefore': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\CreateBefore
          'Neos.Neos.Ui:RemoveNode': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\Remove
          'Neos.Neos.Ui:MoveInto': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\MoveInto
          'Neos.Neos.Ui:MoveAfter': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\MoveAfter
          'Neos.Neos.Ui:MoveBefore': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\MoveBefore
          'Neos.Neos.Ui:CopyInto': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\CopyInto
          'Neos.Neos.Ui:CopyAfter': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\CopyAfter
          'Neos.Neos.Ui:CopyBefore': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\CopyBefore
