Neos:
  EventSourcedNeosAdjustments:
    contentDimensions:
      resolution:
        uriPathSegmentDelimiter: '_'
  Flow:
    http:
      chain:
        preprocess:
          chain:
            detectContentSubgraph:
              component: Neos\EventSourcedNeosAdjustments\EventSourcedRouting\Http\DetectContentSubgraphComponent
    error:
      debugger:
        ignoredClasses:
          'Neos\\ContentRepository\\Domain\\Model\\NodeType': true
          'Neos\\Eel\\CompilingEvaluator': true
          'Neos\\EventSourcedContentRepository\\Domain\\Projection\\Content\\PropertyCollection': true
          'Neos\\Fusion\\FusionObjects\\Helpers\\FusionPathProxy': true
          'Neos\\ContentRepository\\Domain\\Service\\NodeTypeManager': true

  Fusion:
    defaultContext:
      Neos.EventSourcedNeosAdjustments.Workspace: Neos\EventSourcedNeosAdjustments\Fusion\Helper\WorkspaceHelper
      Neos.EventSourcedNeosAdjustments.Node: Neos\EventSourcedNeosAdjustments\Fusion\Helper\NodeHelper
      Neos.EventSourcedNeosAdjustments.Ui.NodeInfo: Neos\EventSourcedNeosAdjustments\Ui\Fusion\Helper\NodeInfoHelper
      Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions: Neos\EventSourcedNeosAdjustments\Ui\Fusion\Helper\ContentDimensionsHelper
  Neos:
    fusion:
      autoInclude:
        Neos.EventSourcedNeosAdjustments: true
    Ui:

      configurationDefaultEelContext:
        Neos.EventSourcedNeosAdjustments.Ui.NodeInfo: Neos\EventSourcedNeosAdjustments\Ui\Fusion\Helper\NodeInfoHelper
        Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions: Neos\EventSourcedNeosAdjustments\Ui\Fusion\Helper\ContentDimensionsHelper

      resources:
        javascript:

          'Neos.EventSourcedNeosAdjustments:Ui.UiAdapter':
            resource: resource://Neos.EventSourcedNeosAdjustments/Public/UiAdapter/Plugin.js


      initialState:
        cr:
          nodes:
            byContextPath: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.defaultNodesForBackend(site, documentNode, controllerContext)}'
            siteNode: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.serializedNodeAddress(site)}'
          contentDimensions:
            # TODO: re-enable dimensions
            byName: '${Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions.contentDimensionsByName()}'
            active: '${documentNode.subgraph.dimensionSpacePoint.coordinates}'
            allowedPresets: '${Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions.allowedPresetsByName(documentNode.subgraph.dimensionSpacePoint)}'
        ui:
          contentCanvas:
            src: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.uri(Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.nodeAddress(documentNode), controllerContext)}'
            contextPath: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.serializedNodeAddress(documentNode)}'
      documentNodeInformation:
        metaData:
          contextPath: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.serializedNodeAddress(documentNode)}'
          siteNode: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.serializedNodeAddress(site)}'

          # TODO Fix!
          previewUrl: ''
          #previewUrl: '${Neos.Ui.NodeInfo.uri(q(documentNode).context({workspaceName: documentNode.context.workspace.baseWorkspace.name}).get(0), controllerContext)}'
          #previewUrl: '${Neos.Ui.NodeInfo.createRedirectToNode(controllerCon

          contentDimensions:
            active: '${documentNode.dimensionSpacePoint.coordinates}'
            allowedPresets: '${Neos.EventSourcedNeosAdjustments.Ui.ContentDimensions.allowedPresetsByName(documentNode.subgraph.dimensionSpacePoint)}'
          documentNodeSerialization: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.renderNodeWithPropertiesAndChildrenInformation(documentNode, controllerContext)}'
          url: '${Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.uri(Neos.EventSourcedNeosAdjustments.Ui.NodeInfo.nodeAddress(documentNode), controllerContext)}'

      changes:
        types:
          'Neos.Neos.Ui:Property': Neos\EventSourcedNeosAdjustments\Ui\Domain\Model\Changes\Property
