Neos:
  ContentGraph:
    DoctrineDbalAdapter:
      persistence:
        backendOptions:
          driver: 'pdo_mysql'
          host: NULL
          dbname: NULL
          user: NULL
          password: NULL
          charset: 'utf8'
