Neos:
  Media:
    thumbnailPresets:
      'Neos.Media.Browser:Thumbnail':
        maximumWidth: 250
        maximumHeight: 250
      'Neos.Media.Browser:Preview':
        maximumWidth: 1000
        maximumHeight: 1000
    Browser:
      bodyClasses: 'neos neos-module media-browser'
      scripts:
        - 'resource://Neos.Neos/Public/Library/jquery/jquery-3.5.1.js'
        - 'resource://Neos.Twitter.Bootstrap/Public/2/js/bootstrap.min.js'
        - 'resource://Neos.Neos/Public/Library/bootstrap-components.js'
        - 'resource://Neos.Media.Browser/Public/JavaScript/media-browser.js'
      styles:
        - 'resource://Neos.Neos/Public/Styles/Neos.css'
        - 'resource://Neos.Media.Browser/Public/Styles/MediaBrowser.css'
        - 'resource://Neos.Media.Browser/Public/Styles/Main.css'

      features:
         # By default, disable the beta feature "variants tab":
        variantsTab:
          enable: false
        # By default, enable the option to create redirects for replaced asset resources
        createAssetRedirectsOption:
          enable: true

  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Neos.Media.Browser:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Neos\Media\Browser\Controller\.*'
    mvc:
      routes:
        'Neos.Media.Browser': true

  Neos:
    modules:
      management:
        submodules:
          media:
            controller: \Neos\Media\Browser\Controller\AssetController
            label: 'Neos.Media.Browser:Main:module.label'
            description: 'Neos.Media.Browser:Main:module.description'
            icon: 'fas fa-camera'
            mainStylesheet: 'Lite'
            privilegeTarget: 'Neos.Media.Browser:ManageAssets'
            additionalResources:
              styleSheets:
                - 'resource://Neos.Media.Browser/Public/Styles/MediaBrowser.css'
                - 'resource://Neos.Media.Browser/Public/Styles/Main.css'
    userInterface:
      translation:
        autoInclude:
          Neos.Media.Browser:
            - 'Main'
