#                                                                        #
# Settings                                                               #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

Neos:
  Media:
    Browser:
      bodyClasses: 'neos neos-module media-browser'
      scripts:
        - 'resource://TYPO3.Neos/Public/Library/jquery/jquery-2.0.3.js'
        - 'resource://Neos.Twitter.Bootstrap/Public/2/js/bootstrap.min.js'
        - 'resource://TYPO3.Neos/Public/Library/bootstrap-components.js'
        - 'resource://Neos.Media.Browser/Public/JavaScript/Modules/media-browser.js'
      styles:
        - 'resource://TYPO3.Neos/Public/Styles/Neos.css'
  Flow:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              'Neos.Media.Browser:BackendControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Neos\Media\Browser\Controller\Backend\.*'
TYPO3:
  Neos:
    modules:
      management:
        submodules:
          media:
            label: 'Neos.Media.Browser:Modules:media.label'
            controller: \Neos\Media\Browser\Controller\Module\Management\AssetController
            description: 'Neos.Media.Browser:Modules:media.description'
            icon: icon-camera
            privilegeTarget: 'Neos.Media.Browser:ManageAssets'
    userInterface:
      translation:
        autoInclude:
          Neos.Media.Browser:
            - Modules
  Media:
    thumbnailPresets:
      'Neos.Media.Browser:Thumbnail':
        maximumWidth: 250
        maximumHeight: 250
      'Neos.Media.Browser:Preview':
        maximumWidth: 1000
        maximumHeight: 1000
