conf.py:
  copyright: '2006-2014, respective authors'
  project: 'TYPO3 Neos'
  release: '1.2'
  version: '1.2'
  latex_documents:
  - - Index
    - typo3.neos.tex
    - TYPO3 Neos Content Management System
    - TYPO3 Neos team
    - manual
  latex_use_parts: 'true'
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
