#                                                                        #
# Default subroutes configuration for the TYPO3CR package                #
#                                                                        #

-
  name: 'REST service with controller and id'
  uriPattern: '{@controller}/{id}(.{@format})'
  defaults:
    '@package':    'TYPO3CR'
    '@subpackage': 'Service'
    '@format':     'json'
    '@action': 'andi'

-
  name: 'REST service with controller'
  uriPattern: '{@controller}(.{@format})'
  defaults:
    '@package':    'TYPO3CR'
    '@subpackage': 'Service'
    '@format':     'json'
