TYPO3:
  TYPO3CR:

    # Configure available content dimensions for nodes, after adding a dimension the database has to be filled with
    # the dimension default values.
    # Also add named presets with fallback chains that can happen in your dimensions.
    #
    # Example
    #
    #   contentDimensions:
    #     language:
    #       default: mul_ZZ
    #       defaultPreset: 'all'
    #       presets:
    #         'all':
    #           values: ['mul_ZZ']
    #
    #     persona:
    #       default: everybody
    #       defaultPreset: 'all'
    #       presets:
    #         'all':
    #           values: ['everybody']
    contentDimensions: []

    # Configures defaults for node label generation
    labelGenerator:
      eel:
        defaultContext:
          String: 'TYPO3\Eel\Helper\StringHelper'
          Array: 'TYPO3\Eel\Helper\ArrayHelper'
          Date: 'TYPO3\Eel\Helper\DateHelper'
          Configuration: 'TYPO3\Eel\Helper\ConfigurationHelper'
          Math: 'TYPO3\Eel\Helper\MathHelper'
          Json: 'TYPO3\Eel\Helper\JsonHelper'
          I18n: 'TYPO3\Flow\I18n\EelHelper\TranslationHelper'

  Flow:
     # Register soft deletable filter & event listeners
    persistence:
      doctrine:
        eventListeners:
          'Gedmo\Timestampable\TimestampableListener':
            events: ['prePersist', 'onFlush', 'loadClassMetadata']
            listener: 'Gedmo\Timestampable\TimestampableListener'

    # Improve debug output for node objects by ignoring large classes
    error:
      debugger:
        ignoredClasses:
          'TYPO3\\TYPO3CR\\Domain\\Service\\NodeTypeManager': TRUE
          'TYPO3\\TYPO3CR\\Domain\\Factory\\NodeFactory': TRUE
          'TYPO3\\TYPO3CR\\Domain\\Service\\Cache\\FirstLevelNodeCache': TRUE